#!/usr/bin/env node

'use strict';

const program = require('commander');
const packageJson = require('./package.json');

program
  .version(packageJson.version)
  .description(packageJson.description)
  .command('add', 'Add a job to a queue')
  .command('process', 'Process jobs in a queue')
  .parse(process.argv);
